// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2QNoOHyK0Cee01hyF7DNpV9t95x5doK4',
    appId: '1:415791615440:web:248cb9d40b511e12e8fdd5',
    messagingSenderId: '415791615440',
    projectId: 'greenery-c3ed7',
    authDomain: 'greenery-c3ed7.firebaseapp.com',
    storageBucket: 'greenery-c3ed7.appspot.com',
    measurementId: 'G-8VD6Q829F0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBIOErKTJVcyCZDUqMzfFtqGxFYigU7X8',
    appId: '1:415791615440:android:a785bf753177d171e8fdd5',
    messagingSenderId: '415791615440',
    projectId: 'greenery-c3ed7',
    storageBucket: 'greenery-c3ed7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB3R3j6EibZEwdi8YRDc5GkoXvafi3kCc',
    appId: '1:415791615440:ios:4bffa1276d83ace4e8fdd5',
    messagingSenderId: '415791615440',
    projectId: 'greenery-c3ed7',
    storageBucket: 'greenery-c3ed7.appspot.com',
    iosClientId: '415791615440-5eiub502e9lt3ger9din14j9eonie0km.apps.googleusercontent.com',
    iosBundleId: 'com.example.greenery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB3R3j6EibZEwdi8YRDc5GkoXvafi3kCc',
    appId: '1:415791615440:ios:4bffa1276d83ace4e8fdd5',
    messagingSenderId: '415791615440',
    projectId: 'greenery-c3ed7',
    storageBucket: 'greenery-c3ed7.appspot.com',
    iosClientId: '415791615440-5eiub502e9lt3ger9din14j9eonie0km.apps.googleusercontent.com',
    iosBundleId: 'com.example.greenery',
  );
}
